Add diagrams
ProgiRade/bytepit-root pull request #19
Opened 2023-12-20 02:59 UTC by JureJurko

2023-12-20 13:48 UTC, fsipic commented on dokumentacija/Dodatak.tex
>  				Dijagram stanja				&  &  &  &  &  &  &  \\
dodaj Franu sate za dijagram stanja i razmješaja

2023-12-20 13:55 UTC, fsipic commented on dokumentacija/Arhitektura.tex
> +			\eject
Mislim da compiler ne uzima podatke iz blob storagea nego ih uzima API, a third party compiler samo kompajlira kod

2023-12-20 14:09 UTC, filipides1 commented on dokumentacija/Dodatak.tex
>  				Dijagram komponenti			&  &  &  &  &  &  &  \\
dodaj Filipu sate za dijagram komponenti

2023-12-20 14:13 UTC, filipides1 commented on dokumentacija/Arhitektura.tex
> +			\eject
Mislim da evaluator komunicira sa BLOB storageom i compilerom

2023-12-20 14:14 UTC, filipides1 requested changes
Dodaj na početak dokumenta u tablicu aktivnosti verziju, što si napravio i datum

2023-12-20 14:21 UTC, fsipic commented on dokumentacija/Arhitektura.tex
> +			\eject
Mislim da je API spojen s blobom

2023-12-20 14:28 UTC, fsipic commented on dokumentacija/Arhitektura.tex
> +			\eject
api je spojen s blobom i s evaluatorom, a evaluator jos s compilerom

2023-12-23 13:21 UTC, JureJurko commented on dokumentacija/Arhitektura.tex
> +			\eject
Evaluator ne treba dodavati s obzirom da je dio web-aplikacije i nije neka vanjska aplikacija poput compilera

2023-12-23 13:25 UTC, JureJurko commented on dokumentacija/Arhitektura.tex
> +			\eject
Dijagram i tekst prepravljeni za dio sa blob storagem i compilerom

2023-12-23 15:48 UTC, filipides1 approved these changes

2023-12-23 15:49 UTC, filipides1 approved these changes

2023-12-23 16:24 UTC, fsipic approved these changes
Lgtm

2023-12-23 16:27 UTC, Maaaarko approved these changes

2023-12-23 16:33 UTC, Maaaarko approved these changes

2023-12-23 16:34 UTC, merged